apiVersion: v1
kind: Secret
metadata:
  name: "watsonx-credentials"
  labels:
    ai-services.io/component: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
type: Opaque
stringData:
  WATSONX_APIKEY: {{ .Values.llm.watsonxApiKey | quote }}
