apiVersion: v1
kind: Service
metadata:
  name: "catalog-ui"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: catalog-ui
spec:
  selector:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/component: catalog-ui
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
      protocol: TCP
