apiVersion: v1
kind: Secret
metadata:
  name: "catalog-secret"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: catalog
type: Opaque
stringData:
  admin-password: {{ .Values.backend.adminPasswordHash | quote }}
