apiVersion: v1
kind: Secret
metadata:
  name: "catalog-db-secret"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: database
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
